[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_recruiter"
version = "0.1.0"
description = "Job Board API"
requires-python = ">=3.8" 